const example = {
  recipes: [
    {
      vegetarian: false,
      vegan: false,
      glutenFree: false,
      dairyFree: false,
      veryHealthy: false,
      cheap: false,
      veryPopular: false,
      sustainable: false,
      lowFodmap: false,
      weightWatcherSmartPoints: 14,
      gaps: "no",
      preparationMinutes: -1,
      cookingMinutes: -1,
      aggregateLikes: 25,
      healthScore: 2,
      creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
      license: "CC BY 3.0",
      sourceName: "Foodista",
      pricePerServing: 140.59,
      extendedIngredients: [
        {
          id: 19334,
          aisle: "Baking",
          image: "light-brown-sugar.jpg",
          consistency: "SOLID",
          name: "brown sugar",
          nameClean: "golden brown sugar",
          original: "2 Tbs brown sugar",
          originalName: "brown sugar",
          amount: 2,
          unit: "Tbs",
          meta: [],
          measures: {
            us: { amount: 2, unitShort: "Tbs", unitLong: "Tbs" },
            metric: { amount: 2, unitShort: "Tbs", unitLong: "Tbs" },
          },
        },
        {
          id: 1001,
          aisle: "Milk, Eggs, Other Dairy",
          image: "butter-sliced.jpg",
          consistency: "SOLID",
          name: "butter",
          nameClean: "butter",
          original: "2 tablespoons butter",
          originalName: "butter",
          amount: 2,
          unit: "tablespoons",
          meta: [],
          measures: {
            us: { amount: 2, unitShort: "Tbsps", unitLong: "Tbsps" },
            metric: { amount: 2, unitShort: "Tbsps", unitLong: "Tbsps" },
          },
        },
        {
          id: 1053,
          aisle: "Milk, Eggs, Other Dairy",
          image: "fluid-cream.jpg",
          consistency: "LIQUID",
          name: "heavy cream",
          nameClean: "cream",
          original: "1 cup heavy cream",
          originalName: "heavy cream",
          amount: 1,
          unit: "cup",
          meta: [],
          measures: {
            us: { amount: 1, unitShort: "cup", unitLong: "cup" },
            metric: {
              amount: 236.588,
              unitShort: "ml",
              unitLong: "milliliters",
            },
          },
        },
        {
          id: 19911,
          aisle: "Cereal",
          image: "maple-syrup.png",
          consistency: "LIQUID",
          name: "maple syrup",
          nameClean: "maple syrup",
          original: "2 tsp maple syrup",
          originalName: "maple syrup",
          amount: 2,
          unit: "tsp",
          meta: [],
          measures: {
            us: { amount: 2, unitShort: "tsps", unitLong: "teaspoons" },
            metric: { amount: 2, unitShort: "tsps", unitLong: "teaspoons" },
          },
        },
        {
          id: 12142,
          aisle: "Nuts;Baking",
          image: "pecans.jpg",
          consistency: "SOLID",
          name: "pecans",
          nameClean: "pecans",
          original: "8 ounces shelled pecans",
          originalName: "shelled pecans",
          amount: 8,
          unit: "ounces",
          meta: ["shelled"],
          measures: {
            us: { amount: 8, unitShort: "oz", unitLong: "ounces" },
            metric: { amount: 226.796, unitShort: "g", unitLong: "grams" },
          },
        },
        {
          id: 93770,
          aisle: "Pasta and Rice;Refrigerated",
          image: "pizza-dough.jpg",
          consistency: "SOLID",
          name: "pizza crust",
          nameClean: "prepared pizza crust",
          original: "1 Mama Mary's Mini Original Pizza Crust",
          originalName: "Mama Mary's Mini Original Pizza Crust",
          amount: 1,
          unit: "",
          meta: ["mini"],
          measures: {
            us: { amount: 1, unitShort: "", unitLong: "" },
            metric: { amount: 1, unitShort: "", unitLong: "" },
          },
        },
        {
          id: 11426,
          aisle: "Baking",
          image: "pumpkin-puree.jpg",
          consistency: "SOLID",
          name: "pumpkin pie mix",
          nameClean: "pumpkin pie mix",
          original: "1/2 cup canned Pumpkin pie filling/mix",
          originalName: "canned Pumpkin pie filling/mix",
          amount: 0.5,
          unit: "cup",
          meta: ["canned"],
          measures: {
            us: { amount: 0.5, unitShort: "cups", unitLong: "cups" },
            metric: {
              amount: 118.294,
              unitShort: "ml",
              unitLong: "milliliters",
            },
          },
        },
        {
          id: 1002035,
          aisle: "Spices and Seasonings",
          image: "garam-masala.jpg",
          consistency: "SOLID",
          name: "pumpkin pie spice",
          nameClean: "pumpkin pie spice",
          original: "1/4 tsp pumpkin pie spice",
          originalName: "pumpkin pie spice",
          amount: 0.25,
          unit: "tsp",
          meta: [],
          measures: {
            us: { amount: 0.25, unitShort: "tsps", unitLong: "teaspoons" },
            metric: { amount: 0.25, unitShort: "tsps", unitLong: "teaspoons" },
          },
        },
      ],
      id: 655525,
      title: "Pecan Pumpkin Pie Dessert Pizza with Maple Whipped Cream",
      readyInMinutes: 45,
      servings: 10,
      sourceUrl:
        "http://www.foodista.com/recipe/YBRFWHCH/pecan-pumpkin-pie-dessert-pizza-with-maple-whipped-cream",
      image: "https://spoonacular.com/recipeImages/655525-556x370.jpg",
      imageType: "jpg",
      summary:
        'Pecan Pumpkin Pie Dessert Pizza with Maple Whipped Cream might be just the <b>Mediterranean</b> recipe you are searching for. For <b>$1.41 per serving</b>, you get a dessert that serves 10. One serving contains <b>394 calories</b>, <b>6g of protein</b>, and <b>29g of fat</b>. <b>Thanksgiving</b> will be even more special with this recipe. 25 people have tried and liked this recipe. From preparation to the plate, this recipe takes around <b>45 minutes</b>. A mixture of brown sugar, pumpkin pie filling/mix, pecans, and a handful of other ingredients are all it takes to make this recipe so delicious. All things considered, we decided this recipe <b>deserves a spoonacular score of 37%</b>. This score is rather bad. Try <a href="https://spoonacular.com/recipes/no-bake-pumpkin-tart-with-maple-pecan-whipped-cream-555266">No-Bake Pumpkin Tart with Maple-Pecan Whipped Cream</a>, <a href="https://spoonacular.com/recipes/maple-and-toasted-pecan-pie-with-maple-whipped-cream-522808">Maple and Toasted Pecan Pie with Maple Whipped Cream</a>, and <a href="https://spoonacular.com/recipes/maple-pumpkin-mini-cheesecakes-with-brown-sugar-maple-whipped-cream-579456">Maple Pumpkin Mini Cheesecakes with Brown Sugar Maple Whipped Cream</a> for similar recipes.',
      cuisines: ["Mediterranean", "Italian", "European"],
      dishTypes: ["dessert"],
      diets: [],
      occasions: ["thanksgiving"],
      instructions:
        "<ol><li>Preheat oven to 425 degrees.</li><li>Melt 1/2 of the butter and 1 tbsp brown sugar in a small skillet.</li><li>Brush onto on side of pizza crust.</li><li>Place on a baking sheet and bake for 3 minutes.</li><li>Meanwhile, add the rest of butter and 1 tbsp brown sugar to the skillet again.</li><li>Once it is melted add pecans and stir.</li><li>Cook for 2-3 minutes over medium until pecans are toasted and coated in sugar. Remove from heat.</li><li>Take crust out of oven and spread pumpkin pie filling evenly on top.</li><li>Sprinkle with pumpkin pie spice.</li><li>Remove pecans from butter mixture and sprinkle evenly on top of pizza.</li><li>Bake for 7 more minutes.</li><li>For Maple Whipped Cream: Using a cold bowl and beaters (I put mine in the freezer for about 30 minutes before using) beat heavy cream and maple syrup on high until stiff peaks form.</li><li>Remove pizza from oven. Cut into 4 pieces. Top with a dollop or two of whipped cream and serve!</li></ol>",
      analyzedInstructions: [
        {
          name: "",
          steps: [
            {
              number: 1,
              step: "Preheat oven to 425 degrees.Melt 1/2 of the butter and 1 tbsp brown sugar in a small skillet.",
              ingredients: [
                {
                  id: 19334,
                  name: "brown sugar",
                  localizedName: "brown sugar",
                  image: "dark-brown-sugar.png",
                },
                {
                  id: 1001,
                  name: "butter",
                  localizedName: "butter",
                  image: "butter-sliced.jpg",
                },
              ],
              equipment: [
                {
                  id: 404645,
                  name: "frying pan",
                  localizedName: "frying pan",
                  image: "pan.png",
                },
                {
                  id: 404784,
                  name: "oven",
                  localizedName: "oven",
                  image: "oven.jpg",
                },
              ],
            },
            {
              number: 2,
              step: "Brush onto on side of pizza crust.",
              ingredients: [
                {
                  id: 93770,
                  name: "prepared pizza crust",
                  localizedName: "prepared pizza crust",
                  image: "pizza-dough.jpg",
                },
              ],
              equipment: [],
            },
            {
              number: 3,
              step: "Place on a baking sheet and bake for 3 minutes.Meanwhile, add the rest of butter and 1 tbsp brown sugar to the skillet again.Once it is melted add pecans and stir.Cook for 2-3 minutes over medium until pecans are toasted and coated in sugar.",
              ingredients: [
                {
                  id: 19334,
                  name: "brown sugar",
                  localizedName: "brown sugar",
                  image: "dark-brown-sugar.png",
                },
                {
                  id: 1001,
                  name: "butter",
                  localizedName: "butter",
                  image: "butter-sliced.jpg",
                },
                {
                  id: 12142,
                  name: "pecans",
                  localizedName: "pecans",
                  image: "pecans.jpg",
                },
                {
                  id: 19335,
                  name: "sugar",
                  localizedName: "sugar",
                  image: "sugar-in-bowl.png",
                },
              ],
              equipment: [
                {
                  id: 404727,
                  name: "baking sheet",
                  localizedName: "baking sheet",
                  image: "baking-sheet.jpg",
                },
                {
                  id: 404784,
                  name: "oven",
                  localizedName: "oven",
                  image: "oven.jpg",
                },
                {
                  id: 404645,
                  name: "frying pan",
                  localizedName: "frying pan",
                  image: "pan.png",
                },
              ],
              length: { number: 6, unit: "minutes" },
            },
            {
              number: 4,
              step: "Remove from heat.Take crust out of oven and spread pumpkin pie filling evenly on top.",
              ingredients: [
                {
                  id: 11426,
                  name: "pumpkin pie mix",
                  localizedName: "pumpkin pie mix",
                  image: "pumpkin-puree.jpg",
                },
                { id: 0, name: "spread", localizedName: "spread", image: "" },
                { id: 0, name: "crust", localizedName: "crust", image: "" },
              ],
              equipment: [
                {
                  id: 404784,
                  name: "oven",
                  localizedName: "oven",
                  image: "oven.jpg",
                },
              ],
            },
            {
              number: 5,
              step: "Sprinkle with pumpkin pie spice.",
              ingredients: [
                {
                  id: 1002035,
                  name: "pumpkin pie spice",
                  localizedName: "pumpkin pie spice",
                  image: "garam-masala.jpg",
                },
              ],
              equipment: [],
            },
            {
              number: 6,
              step: "Remove pecans from butter mixture and sprinkle evenly on top of pizza.",
              ingredients: [
                {
                  id: 1001,
                  name: "butter",
                  localizedName: "butter",
                  image: "butter-sliced.jpg",
                },
                {
                  id: 12142,
                  name: "pecans",
                  localizedName: "pecans",
                  image: "pecans.jpg",
                },
              ],
              equipment: [],
            },
            {
              number: 7,
              step: "Bake for 7 more minutes.For Maple Whipped Cream: Using a cold bowl and beaters (I put mine in the freezer for about 30 minutes before using) beat heavy cream and maple syrup on high until stiff peaks form.",
              ingredients: [
                {
                  id: 1054,
                  name: "whipped cream",
                  localizedName: "whipped cream",
                  image: "whipped-cream.jpg",
                },
                {
                  id: 1053,
                  name: "heavy cream",
                  localizedName: "heavy cream",
                  image: "fluid-cream.jpg",
                },
                {
                  id: 19911,
                  name: "maple syrup",
                  localizedName: "maple syrup",
                  image: "maple-syrup.png",
                },
              ],
              equipment: [
                {
                  id: 404784,
                  name: "oven",
                  localizedName: "oven",
                  image: "oven.jpg",
                },
                {
                  id: 404783,
                  name: "bowl",
                  localizedName: "bowl",
                  image: "bowl.jpg",
                },
              ],
              length: { number: 37, unit: "minutes" },
            },
            {
              number: 8,
              step: "Remove pizza from oven.",
              ingredients: [],
              equipment: [
                {
                  id: 404784,
                  name: "oven",
                  localizedName: "oven",
                  image: "oven.jpg",
                },
              ],
            },
            {
              number: 9,
              step: "Cut into 4 pieces. Top with a dollop or two of whipped cream and serve!",
              ingredients: [
                {
                  id: 1054,
                  name: "whipped cream",
                  localizedName: "whipped cream",
                  image: "whipped-cream.jpg",
                },
              ],
              equipment: [],
            },
          ],
        },
      ],
      originalId: null,
      spoonacularSourceUrl:
        "https://spoonacular.com/pecan-pumpkin-pie-dessert-pizza-with-maple-whipped-cream-655525",
    },
  ],
};

module.exports = example;
